version: '3.8'

services:
  db:
    image: postgres:15
    container_name: etl_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_reporting
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: etl_api
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  pgdata:
